dist: trusty
language: python
python:
  - "3.4"
  - "3.5.2"

before_install:
  - sudo apt-get install wine1.5
  - winetricks python34
  - winetricks python352

script:
  - cd client/
  - wine ./getGameProcess.py < travisTestInput.txt
  